### DISCUSSION TITLE
Candy Cane Effect, plus running xled_plus effects from Home Assistant

### DISCUSSION THREAD

**Discussion by gonzotek** [Anders-Holst/xled_plus#7] [Effects]
I've created my first effect (based quite largely on the Day 11 gradient example).
```
"""
Day 11 mod: Candy Cane
Daily effect, December 11 Modified to resemble a Candy Cane pattern

Red and white sweeping diagonally over the lights.
"""

from xled_plus.samples.sample_setup import *

ctr = setup_control()
if ctr.curr_mode == "movie" or ctr.curr_mode == "playlist":
    ctr.set_mode("off")
ctr.delete_movies()
ctr.set_mode("playlist")

ctr.adjust_layout_aspect(1.0)  # How many times wider than high is the led installation?
cols = [hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.5830, 1.0000, 0.5121), hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.5830, 1.0000, 0.5121), hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.6226, 1.0, -0.5631), hsl_color(0.5830, 1.0000, 0.5121), hsl_color(0.6030, 1.0000, 0.2121)]
GradientSequence(ctr, cols, speed=0.05, folds=0.8, angle=25).launch_movie()

```
Note the section after setup_control doesn't appear in any of the given examples. I was finding that after running launch_movie() four or five times consecutively without using delete_movies was causing the lights set to return an error code.  Also, the tree would flash oddly as the effect was transferred. I found that turning it off, then deleting the movies seemed to eliminate both issues. There's probably better ways to go about this, but it works for me :-)

My setup is a python 3 venv for xled_plus, and a separate directory of each effect I want available in individual {effect_name}.py files, then I call them from a shell script like so:
```
#!/bin/bash
cd /home/pi/xledplus-movies
/home/pi/xledplus/bin/python -m $1
```
I have all of the effects tied to buttons in Home Assistant(note: everything in the "Christmas Tree" and "Favorite Colors" sections are from last year, and don't use any xled_plus code. I'm planning to eventually update them as I have time):
<img width="800" alt="Twinkly + Xled_plus" src="https://user-images.githubusercontent.com/253407/145680498-7ba272c0-1645-46d7-b785-47ec5a5a93a4.png">
Each button calls a Home Assistant shell_command service that then runs the script with the various effects:
Lovelace YAML code for a custom button:
```
      - type: custom:button-card
        tap_action:
          action: call-service
          service: shell_command.set_tree_movie
          service_data:
            movie: candy-cane
        entity: light.christmas_tree
        icon: mdi:candycane
        show_state: false
        name: Candy Cane
        color: rgb(255,10,10)

```

YAML Home Assistant configuration for the shell command:
```
shell_command:
  set_tree_movie: '/home/homeassistant/.homeassistant/scripts/set_tree_movie.sh {{ movie }}'
```
End result(the reds look much better/more saturated in person, and the animation is a nice diagonal swooping of the red/white gradient):
![candy_cane_xled_xmas_tree](https://user-images.githubusercontent.com/253407/145683955-72ffd8d9-b6b6-4c70-b4c4-c50bda15e012.jpg)
